GOARCH ?= "arm"

.PHONY : prepare report imports

all: imports prepare report

imports:
	@echo "==> Create import list"
	go list std | grep -v internal | grep -v "^vendor" > imports

prepare:
	@echo "==> Create test directory"
	mkdir -p tests
	@echo "==> Build report program using $(go env GOROOT)"
	go build gen_import_report.go

report:
	@echo "==> Launch report program using $(go env GOROOT)"
	GOOS=tamago GOARCH=$(GOARCH) ./gen_import_report
	rm -f main

clean:
	rm -rf tests imports gen_import_report import_report.md main
