// AMD64 processor support
// https://github.com/usbarmory/tamago
//
// Copyright (c) The TamaGo Authors. All Rights Reserved.
//
// Use of this source code is governed by the license
// that can be found in the LICENSE file.

#include "go_asm.h"
#include "textflag.h"

// func load_idt() (idt uintptr, irqHandler uintptr)
TEXT ·load_idt(SB),NOSPLIT|NOFRAME,$0-16
	MOVQ	$·gdt(SB), BX

	SUBQ	$16, SP
	SGDT	(SP)
	MOVQ	2(SP), AX
	ADDQ	$16, SP

	// re-use GDT and IDT if cpuinit override is detected
	CMPQ	AX, BX
	JE	reload
reuse:
	// copy code descriptor
	MOVQ	8(BX), CX
	MOVQ	CX, 8(AX)

	// copy data descriptor
	MOVQ	16(BX), CX
	MOVQ	CX, 16(AX)

	// load IDT register
	SUBQ	$16, SP
	SIDT	(SP)

	// save IDT register for APs
	MOVQ	$·idtptr(SB), AX

	// save size
	MOVQ	0(SP), CX
	MOVQ	CX, 0(AX)

	// save offset
	MOVQ	2(SP), CX
	MOVQ	CX, 2(AX)

	ADDQ	$16, SP
	MOVQ	CX, idt+0(FP)
	JMP	done
reload:
	MOVQ	$·idtptr(SB), AX
	LIDT	(AX)

	MOVQ	$·idt(SB), AX
	MOVQ	AX, idt+0(FP)
done:
	// return irqHandler.abi0 pointer
	MOVQ	$·irqHandler(SB), AX
	MOVQ	AX, irqHandler+8(FP)

	STI
	RET

// func wfi()
TEXT ·wfi(SB),NOSPLIT|NOFRAME,$0
	// disable interrupts to avoid races while checking state
	CLI

	MOVB	·irqLock(SB), AX
	CMPB	AX, $1
	JE	done

	// wait for interrupt
	STI
	HLT
done:
	STI
	RET

TEXT ·ignoreInterrupt(SB),NOSPLIT|NOFRAME,$0
	// IRQs to ignore, used to resume halted processors, are generated by:
	//  * ·handleInterrupt to wake idle APs
	//  * CPU.LAPIC.SetTimer at timer expiration
	//  * CPU.SetAlarm with null deadline

	// save caller registers
	PUSHQ	AX

	// clear interrupt
	MOVL	$(const_LAPIC_EOI), AX
	MOVL	$0, (AX)

	// restore caller registers
	POPQ	AX

	// return to caller
	ADDQ	$8, SP
	IRETQ

TEXT ·handleInterrupt(SB),NOSPLIT|NOFRAME,$0
	// save caller registers
	PUSHQ	BX
	PUSHQ	DX
	PUSHQ	CX
	PUSHQ	AX

	// AMD64 Architecture Programmer’s Manual
	// Volume 2 - 8.9.3 Interrupt Stack Frame

	// find ISR offset from stack linking information (see irqHandler)
	MOVQ	isr-(0)(SP), AX
	SUBQ	$(const_callSize), AX
	MOVQ	AX, ·isr(SB)

	MOVB	$1, ·irqHandling(SB)
	MOVB	$1, ·irqLock(SB)

	SUBQ	$8, SP
	MOVQ	$(const_IRQ_SIGNAL), AX
	MOVQ	AX, (SP)
	CALL	os∕signal·Relay(SB)
	ADDQ	$8, SP

	// wake idle APs
	MOVL	$(const_LAPIC_ICRL), AX
	MOVL	$(const_ICR_DST_REST|const_IRQ_WAKEUP), (AX)
done:
	// restore caller registers
	POPQ	AX
	POPQ	CX
	POPQ	DX
	POPQ	BX

	// return to caller
	ADDQ	$8, SP
	MOVB	$0, ·irqHandling(SB)
	IRETQ

TEXT ·handleNMI(SB),NOSPLIT|NOFRAME,$0
	// NMIs are generated by:
	//  * CPU.Task to wake up the next AP (see ·apstart)
	//  * CPU.EnableInterrupt to unmask IRQs on the BSP

	// save caller registers
	PUSHQ	AX

	// clear interrupt
	MOVL	$(const_LAPIC_EOI), AX
	MOVL	$0, (AX)

	// restore caller registers
	POPQ	AX

	// return to caller
	MOVB	$0, ·irqLock(SB)
	IRETQ
