// AMD64 processor support
// https://github.com/usbarmory/tamago
//
// Copyright (c) The TamaGo Authors. All Rights Reserved.
//
// Use of this source code is governed by the license
// that can be found in the LICENSE file.

#include "go_asm.h"
#include "textflag.h"

TEXT ·ret<>(SB),NOSPLIT|NOFRAME,$0
	RET

TEXT ·reload_gdt<>(SB),NOSPLIT|NOFRAME,$0
	MOVQ    $·gdtptr(SB), AX
	LGDT    (AX)

	// reload segment registers
	MOVW	$0x10, AX
	MOVW	AX, DS
	MOVW	AX, ES
	MOVW	AX, GS
	MOVW	AX, SS

	// reload code segment
	MOVQ	$·ret<>(SB), AX
	PUSHQ	$0x08
	PUSHQ	AX
	RETFQ

// func load_idt() (idt uintptr, irqHandler uintptr)
TEXT ·load_idt(SB),$0-16
	MOVQ	$·gdt(SB), BX

	SUBQ	$16, SP
	SGDT	(SP)
	MOVQ	2(SP), AX
	ADDQ	$16, SP

	// ensure that an eventual cpuinit override did load our GDT
	CMPQ	AX, BX
	JE	load
	CALL	·reload_gdt<>(SB)
	STI
load:
	MOVQ	$·idtptr(SB), AX
	LIDT	(AX)

	MOVQ	$·idt(SB), AX
	MOVQ	AX, ret+0(FP)

	// return irqHandler.abi0 pointer
	MOVQ	$·irqHandler(SB), AX
	MOVQ	AX, ret+8(FP)

	RET

// func wfi()
TEXT ·wfi(SB),$0
	// disable interrupts to avoid races while checking state
	CLI

	MOVB	·irqLock(SB), AX
	CMPB	AX, $1
	JE	done

	// wait for interrupt
	STI
	HLT
done:
	STI
	RET

TEXT ·ignoreInterrupt(SB),NOSPLIT|NOFRAME,$0
	// IRQs to ignore, used to resume halted processors, are generated by:
	//  * ·handleInterrupt to wake idle APs
	//  * CPU.LAPIC.SetTimer at timer expiration
	//  * CPU.SetAlarm with null deadline

	// save caller registers
	PUSHQ	AX

	// clear interrupt
	MOVL	$(const_LAPIC_EOI), AX
	MOVL	$0, (AX)

	// restore caller registers
	POPQ	AX

	// return to caller
	ADDQ	$8, SP
	IRETQ

TEXT ·handleInterrupt(SB),NOSPLIT|NOFRAME,$0
	// save caller registers
	PUSHQ	BX
	PUSHQ	DX
	PUSHQ	CX
	PUSHQ	AX

	// AMD64 Architecture Programmer’s Manual
	// Volume 2 - 8.9.3 Interrupt Stack Frame

	// find ISR offset from stack linking information (see irqHandler)
	MOVQ	isr-(0)(SP), AX
	SUBQ	$(const_callSize), AX
	MOVQ	AX, ·isr(SB)

	MOVB	$1, ·irqHandling(SB)
	MOVB	$1, ·irqLock(SB)

	SUBQ	$8, SP
	MOVQ	$(const_IRQ_SIGNAL), AX
	MOVQ	AX, (SP)
	CALL	os∕signal·Relay(SB)
	ADDQ	$8, SP

	// wake idle APs
	MOVL	$(const_LAPIC_ICRL), AX
	MOVL	$(const_ICR_DST_REST|const_IRQ_WAKEUP), (AX)
done:
	// restore caller registers
	POPQ	AX
	POPQ	CX
	POPQ	DX
	POPQ	BX

	// return to caller
	ADDQ	$8, SP
	MOVB	$0, ·irqHandling(SB)
	IRETQ

TEXT ·handleNMI(SB),NOSPLIT|NOFRAME,$0
	// NMIs are generated by:
	//  * CPU.Task to wake up the next AP (see ·apstart)
	//  * CPU.EnableInterrupt to unmask IRQs on the BSP

	// save caller registers
	PUSHQ	AX

	// clear interrupt
	MOVL	$(const_LAPIC_EOI), AX
	MOVL	$0, (AX)

	// restore caller registers
	POPQ	AX

	// return to caller
	MOVB	$0, ·irqLock(SB)
	IRETQ
